### ISSUE TITLE
[Tracking] TTRPG-CLI CSS/SCSS

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/ttrpg-convert-cli#114]
This is just for my things on #113 . Mainly to help me keep track.

What I think is "Done":

- Pf2 Callouts
- Pf2 Admonitions
- Scoped CSS where it would interact with themes.

(I actually so far have not needed to scope anything to specific page-types yet).

What could need work:

- [x] 1. Color cohesion. Everything is pulled from the books but was also made to be more accessible. Thus some things just.. need a design pass.

- [x] 2. Probably a font pass.

What does need work:

- [ ] 1. Trait Shadows for Uncommon.md, Rare.md, and so on. I am not sure how to beat the specificity there. 
- [x] 3. Re-adding a dark theme for the icons. I'll likely get to this tomorrow.
- [x] 4. A specific interaction between embedded callouts where the embedded callout fights with the "parent" callout. I've tried some things but will need to come back to this. 

- [x] 5. Statblock-pf2e

Can be tackled at some point just for completeness. 

- [x] 1. Statblock-5e
- [x] 2. Flowchart Admonition

**Comment by sigrunixia** [comment]
Inadvertently, the update to remove books probably fixed #4.

**Comment by sigrunixia** [comment]
Still trying to fix Uncommon.md so I can do the other "Unique" ones. 

Experienced a regression with Link Icons in dark mode.

**Comment by sigrunixia** [comment]
I noticed after I did some updates to the admonition SCSS, that some admonition padding is way off. I'll get an update in.

**Comment by ebullient** [comment]
A chunk of this (7/8) delivered in 2233ebbb60eddc215805d224b846bcdfa72e830d
